# Generated by Django 4.2.4 on 2023-10-06 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_salesitem_nepali_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='nepali_create_date',
            field=models.CharField(default='19-Aswin-2080', editable=False, max_length=200),
        ),
    ]
