# Generated by Django 4.2.4 on 2023-10-08 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_purchase_nepali_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='nepali_create_date',
            field=models.CharField(default='21-Aswin-2080', max_length=200),
        ),
    ]
