# Generated by Django 4.2.4 on 2023-10-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='remarks',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
