# Generated by Django 4.2.4 on 2023-10-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_payment_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='nepali_create_date',
            field=models.CharField(blank=True, default='21-Aswin-2080', max_length=200, null=True),
        ),
    ]
