# Generated by Django 4.2.4 on 2023-10-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_sales_nepali_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
