# Generated by Django 4.2.4 on 2023-10-09 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_customer_nepali_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nepali_added_date',
            field=models.CharField(default='22-Aswin-2080', max_length=200),
        ),
    ]
