# Generated by Django 4.2.4 on 2023-10-12 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_customer_nepali_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='nepali_added_date',
            field=models.CharField(blank=True, default='25-Aswin-2080', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='nepali_create_date',
            field=models.CharField(default='25 Aswin 2080', max_length=200),
        ),
        migrations.AlterField(
            model_name='inventoryproduct',
            name='nepali_create_date',
            field=models.CharField(default='25 Aswin 2080', max_length=200),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='nepali_create_date',
            field=models.CharField(blank=True, default='25-Aswin-2080', editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='nepali_create_date',
            field=models.CharField(blank=True, default='25-Aswin-2080', editable=False, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseparty',
            name='nepali_create_date',
            field=models.CharField(default='25 Aswin 2080', max_length=200),
        ),
        migrations.AlterField(
            model_name='sales',
            name='nepali_create_date',
            field=models.CharField(blank=True, default='25-Aswin-2080', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='nepali_create_date',
            field=models.CharField(default='25-Aswin-2080', max_length=200),
        ),
        migrations.CreateModel(
            name='DailyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nepali_date', models.CharField(default='25-Aswin-2080', max_length=200)),
                ('quantity', models.FloatField(default=1)),
                ('total_amount', models.FloatField()),
                ('remarks', models.TextField()),
                ('product', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_product', to='app.product')),
            ],
            options={
                'ordering': ['-nepali_date'],
            },
        ),
    ]
