# Generated by Django 4.2.4 on 2023-10-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_dailytransaction_unite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
