# Generated by Django 4.2.4 on 2023-10-12 08:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_purchaseitem_quantity_alter_salesitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toll',
            name='toll_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, populate_from='toll_name', unique=True),
        ),
    ]
