# Generated by Django 4.2.4 on 2023-10-12 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_toll_toll_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nepali_date', models.CharField(blank=True, default='25-Aswin-2080', max_length=200, null=True)),
            ],
            options={
                'ordering': ['-nepali_date'],
            },
        ),
        migrations.AlterModelOptions(
            name='dailytransaction',
            options={'ordering': ['-dailyid']},
        ),
        migrations.RemoveField(
            model_name='dailytransaction',
            name='nepali_date',
        ),
        migrations.AddField(
            model_name='dailytransaction',
            name='dailyid',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='dailyId', to='app.daily'),
            preserve_default=False,
        ),
    ]
