# Generated by Django 4.2.4 on 2023-10-12 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_daily_alter_dailytransaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='nepali_date',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
