# Generated by Django 4.2.4 on 2023-10-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_dailytransaction_dailyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
