# Generated by Django 4.2.4 on 2023-11-02 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_alter_customer_nepali_added_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='nepali_date',
            field=models.CharField(blank=True, default='16 Kartik 2080', editable=False, max_length=200, null=True),
        ),
    ]
