# Generated by Django 4.2.4 on 2023-11-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_daily_nepali_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='nepali_date',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
