# Generated by Django 4.2.4 on 2023-11-02 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_daily_nepali_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytransaction',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailytransaction',
            name='unite',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_product_unit', to='app.productunit'),
        ),
    ]
