# Generated by Django 4.2.4 on 2023-11-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_alter_dailytransaction_total_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytransaction',
            name='total_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
