# Generated by Django 4.2.4 on 2023-11-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_dailytransaction_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytransaction',
            name='total_amount',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
