# Generated by Django 4.2.4 on 2023-11-03 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_alter_expenses_amount_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='amount_per_unit',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sales',
            name='paid_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='remaining_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_amount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
