# Generated by Django 4.2.4 on 2023-11-03 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_alter_expenses_amount_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='bill_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='paid_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='remaining_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='total_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
