# Generated by Django 4.2.4 on 2023-09-03 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_alter_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_editor',
            new_name='is_admin',
        ),
    ]
